### ISSUE TITLE
SignedContentFromBundleFile.checkValidity is empty

### ISSUE THREAD

**Issue by tjwatson** [eclipse-equinox/equinox.framework#3]
In the mitration to using the JarFile implementation for SignedContent implementation it seems the method checkValidity was never implemented.  This was discovered by @merks

I'm not sure how this was missed.  It does not appear we have any negative tests that try to validate a JAR with an invalid signing date.

**Comment by merks** [comment]
FYI, I think it could be implemented like this:
```
	@Override
	public void checkValidity(SignerInfo signerInfo)
			throws CertificateExpiredException, CertificateNotYetValidException {
		Date signingTime = getSigningTime(signerInfo);
		Certificate[] certs = signerInfo.getCertificateChain();
		for (Certificate cert : certs) {
			if (!(cert instanceof X509Certificate)) {
				continue;
			}
			if (signingTime == null) {
				((X509Certificate) cert).checkValidity();
			} else {
				((X509Certificate) cert).checkValidity(signingTime);
			}
		}
	}
```

**Comment by tjwatson** [comment]
The original code had some strange boolean flag it set to avoid rechecking.  That seems horribly incorrect behavior for this method given any number of SingerInfo could be passed to the method.  As soon as one doesn't throw an exception it would set to true and never check any other signer ever.

**Comment by merks** [comment]
That was quick!  Thanks!!
