### ISSUE TITLE
112 failed tests in today I-build

### ISSUE THREAD

**Issue by akurtakov** [eclipse-equinox/equinox.framework#47]
https://download.eclipse.org/eclipse/downloads/drops4/I20220503-1930/testresults/html/org.eclipse.osgi.tests_ep424I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html
@HannesWell , sounds related to tonight's build failure and fix?

**Comment by HannesWell** [comment]
Thanks Tom.

I don't want to deny that this is caused by the recent osgi-bundle replacement, but from the error messages I cannot tell for sure this is the cause because the stacktrace only tells me those tests are not executed.

**Comment by tjwatson** [comment]
> I don't want to deny that this is caused by the recent osgi-bundle replacement, but from the error messages I cannot tell for sure this is the cause because the stacktrace only tells me those tests are not executed.

If you go to the console logs for the osgi.tests (for example [here](https://download.eclipse.org/eclipse/downloads/drops4/I20220503-1930/testresults/ep424I-unit-mac64-java17_macosx.cocoa.x86_64_17/org.eclipse.osgi.tests.AutomatedTests.txt) you will find resolution failures like this:

```
!ENTRY org.eclipse.core.tests.harness 4 0 2022-05-04 01:55:19.954
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.core.tests.harness [8]
  Unresolved requirement: Require-Bundle: org.eclipse.test.performance; resolution:="optional"
    -> Bundle-SymbolicName: org.eclipse.test.performance; bundle-version="3.18.0.v20210623-0710"
       org.eclipse.test.performance [18]
         Unresolved requirement: Require-Bundle: org.eclipse.core.runtime
           -> Bundle-SymbolicName: org.eclipse.core.runtime; bundle-version="3.25.0.v20220422-2114"; singleton:="true"
              org.eclipse.core.runtime [2]
                Unresolved requirement: Require-Bundle: org.eclipse.core.contenttype; bundle-version="[3.8.0,4.0.0)"; visibility:="reexport"
                  -> Bundle-SymbolicName: org.eclipse.core.contenttype; bundle-version="3.8.100.v20210910-0640"; singleton:="true"
                     org.eclipse.core.contenttype [6]
                       Unresolved requirement: Require-Bundle: org.eclipse.equinox.preferences; bundle-version="[3.2.0,4.0.0)"
                         -> Bundle-SymbolicName: org.eclipse.equinox.preferences; bundle-version="3.10.0.v20220503-1634"; singleton:="true"
                            org.eclipse.equinox.preferences [5]
                              Unresolved requirement: Require-Bundle: org.osgi.service.prefs; bundle-version="[1.1.0,1.2.0)"; visibility:="reexport"
```

**Comment by HannesWell** [comment]
Thanks for that hint. Then it is clear.
