### ISSUE TITLE
BundleLoader buddy loading not consistent

### ISSUE THREAD

**Issue by jan-pesta** [eclipse-equinox/equinox.framework#52]
Hi,

With new feature to resolve classes by annotations Budy policy loading is not consistent.

BundleLoader.findResource(pkgName) is able to resolve package in registered buddy.

But when I want to list resources method listResources(), policy is not checked and I am unable to get classes from registered buddy.

Actually this mechanism is used by Log4J where it is failing to load custom classes.

**Comment by tjwatson** [comment]
What `listResources` method are you referring to?  I assume `org.osgi.framework.wiring.BundleWiring.listResources(String, String, int)`.  How is Log4J calling that?

**Comment by jan-pesta** [comment]
Yes, I am reffering that method.

It is used by logging-log4j2/blob/release-2.x/log4j-core/src/main/java/org/apache/logging/log4j/core/config/plugins/util/ResolverUtil.java

in method  loadImplementationsInBundle, which is calling BundleWiring.listResources which ends in BundleLoader

**Comment by jan-pesta** [comment]
Yes, I think registered policy would be enough.
