### ISSUE TITLE
Incorrect org.osgi Maven-dependencies in generated pom of o.e.osgi.util

### ISSUE THREAD

**Issue by HannesWell** [eclipse-equinox/equinox.framework#70]
Just like o.e.equinox.preferences (handled https://github.com/eclipse-equinox/equinox.bundles/issues/54) `org.eclipse.osgi.util` also uses wrong groudIds (`org.osgi.util` instead of `org.osgi`) for the newly introduced osgi dependencies from Maven-Central:
https://repo1.maven.org/maven2/org/eclipse/platform/org.eclipse.osgi.util/3.7.0/org.eclipse.osgi.util-3.7.0.pom

Given that the publication processes was fixed already with https://github.com/eclipse-platform/eclipse.platform.releng/pull/48/ it likely only requires a re-build and re-publication of `org.eclipse.osgi.util.

@sravanlakkimsetti @akurtakov can you please take care of this again.

**Comment by HannesWell** [comment]
From this PR https://github.com/eclipse-equinox/equinox.bundles/pull/26 the following bundles should be affected as well::
- org.eclipse.equinox.log.stream:
https://repo1.maven.org/maven2/org/eclipse/platform/org.eclipse.equinox.log.stream/1.1.0/org.eclipse.equinox.log.stream-1.1.0.pom
- org.eclipse.equinox.coordinator:
https://repo1.maven.org/maven2/org/eclipse/platform/org.eclipse.equinox.coordinator/1.5.0/org.eclipse.equinox.coordinator-1.5.0.pom

But their poms seem not to contain any dependency. Likely because the osgi-bundles are required via Import-Package and not require bundle. I wonder if this is an error in the generator as well.

**Comment by bjhargrave** [comment]
> I wonder if this is an error in the generator as well.

That would be bad and needs to be fixed. All the OSGi artifacts contain the maven metadata under `META-INF/maven` so a generator tool can always find the correct maven coordinates for an OSGi artifact.

**Comment by akurtakov** [comment]
IMHO we should not use generator postfactum but during the build that would embed good pom.xml file in META-INF/maven at build time and later use this one to deploy.

**Comment by HannesWell** [comment]
> > I wonder if this is an error in the generator as well.
> 
> That would be bad and needs to be fixed. All the OSGi artifacts contain the maven metadata under `META-INF/maven` so a generator tool can always find the correct maven coordinates for an OSGi artifact.

IIRC all jars deployed to Maven-Central have their pom embedded. So instead of relying on rules that have to be crafted for all dependencies the pom generator could check for those poms and derive the GAV from it.

**Comment by laeubi** [comment]
I recommended that awhile ago but it has not got much attention (until today), the problem is that the post-script making some assumptions, and the jars in question either don't contain pom or just "bad pom" data at the moment.

**Comment by akurtakov** [comment]
> > > I wonder if this is an error in the generator as well.
> > 
> > 
> > That would be bad and needs to be fixed. All the OSGi artifacts contain the maven metadata under `META-INF/maven` so a generator tool can always find the correct maven coordinates for an OSGi artifact.
> 
> IIRC all jars deployed to Maven-Central have their pom embedded. So instead of relying on rules that have to be crafted for all dependencies the pom generator could check for those poms and derive the GAV from it.

Generator tool was written years ago at the time when using Maven Central was not directly usable and Orbit artifacts didn't contain this information. Unfortunately, it hasn't evolved since then and we are probably better relying on Tycho to do that part instead.

**Comment by laeubi** [comment]
> > I recommended that awhile ago but it has not got much attention (until today)
> 
> It got attention and support; but no workforce as it wasn't a serious problem before today.

Don't wanted to accuse anyone here, just noted that the idea itself is not quite new, and I fear that the underlying problem (no workforce as it wasn't a serious problem) still remains.

Anyways I'll try starting with equinox but there will be probably some more to do at Tycho as well to support it best (e.g. https://github.com/eclipse/tycho/discussions/1015 ...)

**Comment by akurtakov** [comment]
> Relaying on Tycho sounds even better. And I didn't want to blame anyone, just suggest an improvement for the future. :)

Not taken as blaming someone at all. There are tons of things that are stale in the past combined with not many people trying to modernize things (in a graceful way!) and community slow on adapting new things and  we came to what we see today.

**Comment by sravanlakkimsetti** [comment]
Deployed new version https://repo1.maven.org/maven2/org/eclipse/platform/org.eclipse.osgi.util/3.7.1/

**Comment by HannesWell** [comment]
Geräte! Thank you for this extra effort.All osgi dependencies I'm aware of should bei fixed now.Am 15.06.2022 19:42 schrieb Sravan Kumar Lakkimsetti ***@***.***>:
Deployed new version https://repo1.maven.org/maven2/org/eclipse/platform/org.eclipse.osgi.util/3.7.1/

**Comment by sravanlakkimsetti** [comment]
Raised https://issues.sonatype.org/browse/OSSRH-81766 to get offending artifacts removed. Lets wait for maven central to act there

**Comment by sravanlakkimsetti** [comment]
> Raised https://issues.sonatype.org/browse/OSSRH-81766 to get offending artifacts removed. Lets wait for maven central to act there

the offending artifacts have been removed from maven central. Please try now
